[tool.poetry]
name = "pentool"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.2"
annotated-types = "0.7.0"
anyio = "4.6.1"
argon2-cffi = "23.1.0"
argon2-cffi-bindings = "21.2.0"
arrow = "1.3.0"
asttokens = "2.4.1"
async-lru = "2.0.4"
attrs = "24.2.0"
babel = "2.16.0"
beautifulsoup4 = "4.12.3"
bleach = "6.1.0"
build = "1.2.2.post1"
cachecontrol = "0.14.0"
certifi = "2024.8.30"
cffi = "1.17.1"
chardet = "5.2.0"
charset-normalizer = "3.4.0"
cleo = "2.1.0"
click = "8.1.7"
colorama = "0.4.6"
comm = "0.2.2"
contourpy = "1.3.0"
crashtest = "0.4.1"
cycler = "0.12.1"
debugpy = "1.8.7"
decorator = "5.1.1"
defusedxml = "0.7.1"
distlib = "0.3.9"
dulwich = "0.21.7"
executing = "2.1.0"
fastjsonschema = "2.20.0"
filelock = "3.16.1"
fonttools = "4.54.1"
fqdn = "1.5.1"
h11 = "0.14.0"
httpcore = "1.0.6"
httpx = "0.27.2"
idna = "3.10"
installer = "0.7.0"
ipykernel = "6.29.5"
ipython = "8.28.0"
ipywidgets = "8.1.5"
isoduration = "20.11.0"
jaraco-classes = "3.4.0"
jedi = "0.19.1"
jinja2 = "3.1.4"
joblib = "1.4.2"
json5 = "0.9.25"
jsonpointer = "3.0.0"
jsonschema = "4.23.0"
jsonschema-specifications = "2024.10.1"
jupyter = "1.1.1"
jupyter-console = "6.6.3"
jupyter-events = "0.10.0"
jupyter-lsp = "2.2.5"
jupyter-client = "8.6.3"
jupyter-core = "5.7.2"
jupyter-server = "2.14.2"
jupyter-server-terminals = "0.5.3"
jupyterlab = "4.2.5"
jupyterlab-pygments = "0.3.0"
jupyterlab-server = "2.27.3"
jupyterlab-widgets = "3.0.13"
keyring = "24.3.1"
kiwisolver = "1.4.7"
markupsafe = "3.0.1"
matplotlib = "3.9.2"
matplotlib-inline = "0.1.7"
mistune = "3.0.2"
more-itertools = "10.5.0"
msgpack = "1.1.0"
nbclient = "0.10.0"
nbconvert = "7.16.4"
nbformat = "5.10.4"
nest-asyncio = "1.6.0"
notebook = "7.2.2"
notebook-shim = "0.2.4"
numpy = "2.1.2"
overrides = "7.7.0"
packaging = "24.1"
pandas = "2.2.3"
pandocfilters = "1.5.1"
parso = "0.8.4"
pexpect = "4.9.0"
pillow = "10.4.0"
pipenv = "2024.1.0"
pkginfo = "1.11.2"
platformdirs = "4.3.6"
plotly = "5.24.1"
poetry = "1.8.3"
poetry-core = "1.9.0"
poetry-plugin-export = "1.8.0"
prometheus-client = "0.21.0"
prompt-toolkit = "3.0.48"
psutil = "6.0.0"
ptyprocess = "0.7.0"
pure-eval = "0.2.3"
pycparser = "2.22"
pydantic = "2.9.2"
pydantic-core = "2.23.4"
pygments = "2.18.0"
pyparsing = "3.2.0"
pyproject-hooks = "1.2.0"
python-dateutil = "2.9.0.post0"
python-json-logger = "2.0.7"
pytz = "2024.2"
pywin32 = "308"
pywin32-ctypes = "0.2.3"
pywinpty = "2.0.13"
pyyaml = "6.0.2"
pyzmq = "26.2.0"
rapidfuzz = "3.10.0"
referencing = "0.35.1"
requests = "2.32.3"
requests-toolbelt = "1.0.0"
rfc3339-validator = "0.1.4"
rfc3986-validator = "0.1.1"
rpds-py = "0.20.0"
scikit-learn = "1.5.2"
scipy = "1.14.1"
seaborn = "0.13.2"
send2trash = "1.8.3"
setuptools = "75.1.0"
shellingham = "1.5.4"
six = "1.16.0"
sniffio = "1.3.1"
soupsieve = "2.6"
stack-data = "0.6.3"
starlette = "0.39.2"
tabulate = "0.9.0"
tenacity = "9.0.0"
terminado = "0.18.1"
threadpoolctl = "3.5.0"
tinycss2 = "1.3.0"
tomlkit = "0.13.2"
tornado = "6.4.1"
traitlets = "5.14.3"
trove-classifiers = "2024.10.13"
types-python-dateutil = "2.9.0.20241003"
typing-extensions = "4.12.2"
tzdata = "2024.2"
uri-template = "1.3.0"
urllib3 = "2.2.3"
uvicorn = "0.31.1"
virtualenv = "20.26.6"
wcwidth = "0.2.13"
webcolors = "24.8.0"
webencodings = "0.5.1"
websocket-client = "1.8.0"
wheel = "0.44.0"
widgetsnbextension = "4.0.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
